spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_microservicios_usuarios
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: ms-usuarios


logging:
  level.org.hibernate.SQL: debug

server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defautZone: http://localhost:8761/eureka
