spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_ms_respuestas
  application:
    name: ms-respuestas
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defautZone: http://localhost:8761/eureka
